### ISSUE TITLE
Crash when cannot determine file format

### ISSUE THREAD

**Issue by ygbillet** [photo-cli/photo-cli#14]
Hi,

I just try your program on my 15k+ photos
Got an error when trying to organize my collection with : `photo-cli copy --process-type FlattenAllSubFolders --group-by YearMonthDay --naming-style DateTimeWithSeconds --number-style OnlySequentialNumbers --input Phones --output organized`

```
Parsing photo exif information: 5% - (738/15087)
Unhandled exception. MetadataExtractor.ImageProcessingException: File format could not be determined
   at MetadataExtractor.ImageMetadataReader.ReadMetadata(Stream stream)
   at PhotoCli.Services.Implementations.ExifParserService.Parse(String filePath, Boolean parseDateTime, Boolean parseCoordinate) in /home/runner/work/photo-cli/photo-cli/src/Services/Implementations/ExifParserService.cs:line 46
   at PhotoCli.Services.Implementations.ExifDataAppenderService.ExifDataByPath(IEnumerable`1 photoPaths, Boolean& allPhotosHasPhotoTaken, Boolean& allPhotosHasCoordinate) in /home/runner/work/photo-cli/photo-cli/src/Services/Implementations/ExifDataAppenderService.cs:line 25
   at PhotoCli.Runners.CopyRunner.Execute() in /home/runner/work/photo-cli/photo-cli/src/Runners/CopyRunner.cs:line 65
   at PhotoCli.Program.MainWithServiceProvider(IServiceProvider serviceProvider) in /home/runner/work/photo-cli/photo-cli/src/Program.cs:line 140
   at PhotoCli.Program.<Main>(String[] args)
Aborted
```

**Comment by alpcoker** [comment]
Hi @ygbillet ,

Thank you for your interest and for reporting this error. It seems like, one of the photos you have can't read by that [internal library](https://github.com/drewnoakes/metadata-extractor-dotnet) that I used. 

I haven't faced with my any photos so I missed this error. I will handle this error and move this photo to another folder with a name like `not-categorized`, or `not-determined-format`.  I will try to fix this error this week and publish a preview version that fixes this problem. I will reply to this issue and would love you to try again.

**Comment by alpcoker** [comment]
Hello @ygbillet 

I have solved the issue with a new argument. As I haven't completed the documentation I wanted to give quick feedback about how you will use that argument.

On the `copy` verb, I have added an optional argument `--invalid-format` or `-x` with the values of. 

```
public enum CopyInvalidFormatAction : byte
{
	Continue = 0,
	PreventProcess = 1,
	DontCopyToOutput = 2,
	InSubFolder = 3,
}
```

- Default is `Continue = 0` . It will copy your invalid/unreadable formatted photo to output without no naming. Your command should now work without giving an error and copy an invalid/unknown formatted photo to the root output folder.

- `PreventProcess = 1` breaks processing. 
- `DontCopyToOutput = 2` will filter and copy/process only readable formats. Will give you the list of files that is not readable.
- `InSubFolder = 3` will put invalid/unreadable photos in a separate folder.

I have published a preview version. You can update to preview by the following command;

```
dotnet tool update --global photo-cli --version 0.1.0-preview2
```

I will be very happy if you share your feedback.
